server:
  port: 7000

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: student-service
              uri: lb://STUDENT-SERVICE
              predicates:
                - Path=/api/v1/students
            - id: student-service-wildcard
              uri: lb://STUDENT-SERVICE
              predicates:
                - Path=/api/v1/students/**
            - id: program-service
              uri: lb://PROGRAM-SERVICE
              predicates:
                - Path=/api/v1/programs
            - id: program-service-wildcard
              uri: lb://PROGRAM-SERVICE
              predicates:
                - Path=/api/v1/programs/**
            - id: enrollment-service
              uri: lb://ENROLLMENT-SERVICE
              predicates:
                - Path=/api/v1/enrollments
            - id: enrollment-service-wildcard
              uri: lb://ENROLLMENT-SERVICE
              predicates:
                - Path=/api/v1/enrollments/**
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
