spring:
  application:
    name: Config-Server


  cloud:
    config:
      server:
        git:
          uri: https://github.com/thushini21/Capstone-Project-Configurations.git
          search paths: platform, services
        native:
          search-locations:
            - classpath:/Configurations
            - classpath:/Configurations/platform
            - classpath:/Configurations/services

server:
  port: 9000

