server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eca
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  storage:
    path: ${user.home}/.ijse/eca/students
